### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by fabiosirna** [fabiospampinato/notable#164]
I've got this error:

```
TypeError: Cannot read property 'path' of undefined
    at get (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/src/renderer/components/main/sidebar/tag_single.tsx:38:31)
    at SelectorComponent.shouldComponentUpdate (/private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/node_modules/react-selectr/src/index.tsx:17:7)
    at shouldComponentUpdate (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:135:104)
    at Wf (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:160:1)
    at wg (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:169:427)
    at Ag (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)
    at Qh (file:///private/var/folders/0r/j3_v6m7s0z70j_lnclkd0zw0324dbc/T/AppTranslocation/C5AD0E9C-F894-4CED-8A3E-661BFF7033EB/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:216:196)
```

**Comment by fabiospampinato** [comment]
@fabiosirna can you reproduce the issue right after starting-up the app? If so do you have any steps to reproduce the issue?

**Comment by fabiosirna** [comment]
Today It happened everytime I delete a notes from a notebook. I'll try to reproduce it and came back to you. BTW really nice app, feel free to contact me if you need help for the design part :)

**Comment by fabiosirna** [comment]
To reproduce it:

- create a new note, call it Test 1 and assign a notebook like Notebooks/Test
- create a new note, call it Test 2 and assign a notebook like Notebooks/Test
- delete Test 2
- delete Test 1

and you get the error

**Comment by fabiospampinato** [comment]
@fabiosirna thanks, I'll try to reproduce the issue.

> BTW really nice app, feel free to contact me if you need help for the design part :)

Thank you :) If you have any suggestion on the design front I'll be happy to hear those. My humble opinion as a non-designer is that the app looks pretty good already, expect the toolbars which look a bit off to me, and the multi-note editor.

**Comment by fabiospampinato** [comment]
@fabiosirna I can't reproduce the issue anymore, I think I may have fixed this already, as I also saw similar steps leading to a crash in earlier builds.

Feel free to re-open this issue if the problem persists in v1.1.0 (maybe I'll publish this today).

**Comment by fabiospampinato** [comment]
@fabiosirna whatever works best for you, my email is spampinabio@gmail.com.

**Comment by fabiosirna** [comment]
@fabiospampinato with the latest version I can't reproduce the bug, so I think you fixed it ;)
