### ISSUE TITLE
Help > "About" > App Crashes!!!!!!!!!!

### ISSUE THREAD

**Issue by nine1one** [fabiospampinato/notable#1686]
## Issue Summary

Application crashes when attempting to open the "About" section from "Help" in the menu bar.

## System Information
- **Operating System**: Windows 11 Pro Version 23H2, build	25387.1 [Windows Feature Experience Pack 1000.25350.1000.0]
- **Notable Version**: v1.9.0-beta.10 

## Current Behavior

When I run the app, click on "Help > About" from the menu bar, the application crashes. I briefly see the logo of the application, which I believe is part of the "About" section, before the crash occurs.

## Expected Behavior

The "About" section should open without causing the application to crash.

## Additional Information

Based on an analysis with ChatGPT and the data from DevTools/Console, it was suggested that this issue could be related to a conflict with the Squirrel updater that is used by many Electron apps for managing updates. The application might be trying to call the Squirrel updater to check for updates when "Help > About" is selected, causing the crash.

I've tried the following troubleshooting steps:

1. Running the application as an administrator.
2. Reinstalling the application with the latest stable version.
3. Checked for antivirus or firewall interference.
Later found the following.

## Error:

2renderer.eb130228ba9a9a47fd0d.js:37 Error: Can not find Squirrel
    at Object.m [as castError] (renderer.eb130228ba9a9a47fd0d.js:3:1491)
    at Object.make (renderer.eb130228ba9a9a47fd0d.js:37:26790)
    at Object.silent (renderer.eb130228ba9a9a47fd0d.js:37:26538)
    at onError (renderer.eb130228ba9a9a47fd0d.js:69:51706)
    at i (renderer.eb130228ba9a9a47fd0d.js:1007:125975)
    at execute (renderer.eb130228ba9a9a47fd0d.js:1007:124247)
    at o.apply (renderer.eb130228ba9a9a47fd0d.js:1007:123948)
    at Object.apply (renderer.eb130228ba9a9a47fd0d.js:1007:121575)
    at Object.trigger (renderer.eb130228ba9a9a47fd0d.js:69:21811)
    at Object.trigger (renderer.eb130228ba9a9a47fd0d.js:20:12599)
    at Object.call (renderer.eb130228ba9a9a47fd0d.js:20:12104)
    at o (renderer.eb130228ba9a9a47fd0d.js:1013:28374)
    at EventEmitter.onCall (renderer.eb130228ba9a9a47fd0d.js:178:49151)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)
silent @ renderer.eb130228ba9a9a47fd0d.js:37

**Comment by nine1one** [comment]
Not using the App Anymore
