### ISSUE TITLE
Error report: These sources are not supported: C:\Users\cr070\Downloads\DG230528.HTM

### ISSUE THREAD

**Issue by yutakida** [fabiospampinato/notable#1687]
- **OS Version**: win32 10.0.23481
- **Notable Version**: v1.8.4

```
Error: These sources are not supported: C:\Users\cr070\Downloads\DG230528.HTM
    at Object.dump (file:///C:/Users/cr070/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201495)
    at import_Import.import (file:///C:/Users/cr070/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:2:24295)
```
[ラップ平均値 (1).xlsx](https://github.com/notable/notable/files/11812040/1.xlsx)

**Comment by fabiospampinato** [comment]
Can you check if you see the same error in beta10? https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10
