### ISSUE TITLE
Error report: File too large, try splitting it into smaller ones

### ISSUE THREAD

**Issue by lucyellu** [fabiospampinato/notable#1690]
- **OS Version**: win32 10.0.22000
- **Notable Version**: v1.9.0-beta.1

```
Error: File too large, try splitting it into smaller ones
    at file:///C:/Users/lucyl/OneDrive/Downloads/Install/Notable-1.9.0-beta.1-win/resources/app.asar/renderer/chunk.eb0308129f5561d560bd.js:1:2440
    at async Object.read (file:///C:/Users/lucyl/OneDrive/Downloads/Install/Notable-1.9.0-beta.1-win/resources/app.asar/renderer/chunk.eb0308129f5561d560bd.js:1:2528)
    at async i.dump (file:///C:/Users/lucyl/OneDrive/Downloads/Install/Notable-1.9.0-beta.1-win/resources/app.asar/renderer/chunk.eb0308129f5561d560bd.js:1:4088)
    at async Object.dump (file:///C:/Users/lucyl/OneDrive/Downloads/Install/Notable-1.9.0-beta.1-win/resources/app.asar/renderer/chunk.eb0308129f5561d560bd.js:1:594)
```

**Comment by fabiospampinato** [comment]
Beta10 is the latest beta, I'd recommend updating (https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10). Other than that the error is not really fixable on our end in general, I think, you'd just have to export and reimport your notes in smaller chunks.
