### ISSUE TITLE
An Error Occurred!

### ISSUE THREAD

**Issue by phwelo** [fabiospampinato/notable#184]
```
TypeError: Cannot read property 'path' of undefined
    at get (file:///opt/Notable/resources/app.asar/webpack:/src/renderer/components/main/sidebar/tag_single.tsx:38:31)
    at SelectorComponent.shouldComponentUpdate (/opt/Notable/resources/app.asar/node_modules/react-selectr/src/index.tsx:17:7)
    at shouldComponentUpdate (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:135:104)
    at Wf (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:160:1)
    at wg (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:169:427)
    at Ag (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)
    at Qh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:216:196)
```

since my only option is to "report it" i thought i would:)

of note: i had just deleted all notes when this happened

**Comment by fabiospampinato** [comment]
This is probably fixed already. Check if the problem reproduces itself in v1.1.0 (it should auto-update itself, or at least it did it for me).
