### ISSUE TITLE
App crashing on searching 'Notable'

### ISSUE THREAD

**Issue by LECZYF** [fabiospampinato/notable#21]
Hi,

Using Notable.1.0.1.exe on Window 7 64 bit. After opening an app I wrote 'Notable' in search bar and pressed enter, after that an error occured with log as below:

`Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Error (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:13:314)
    at ca (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at t (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:118:40)
    at af (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:150:11)
    at fg (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:154:21)
    at Q (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:468)
    at Ag (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///C:/Users/User/AppData/Local/Temp/nstEF44.tmp/app/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)`

**Comment by sletap** [comment]
App crashes anytime you search for a word and then click enter. Doesn't matter whether a query is found or not. 
Window 10 64 bit

**Comment by sevzero** [comment]
Same thing happening to me on Arch.

**Comment by johnletey** [comment]
Same thing happening to me on OSX 10.14. For me, as long as you don't hit enter you'll be able to search just fine, but if you do hit enter the app crashes.

**Comment by fabiospampinato** [comment]
> as long as you don't hit enter you'll be able to search just fine, but if you do hit enter the app crashes.

That's interesting, the enter key should be completely ignored by the app actually 🤔

**Comment by roccowang** [comment]
> > as long as you don't hit enter you'll be able to search just fine, but if you do hit enter the app crashes.
> 
> That's interesting, the enter key should be completely ignored by the app actually 🤔

@fabiospampinato you mean hitting enter wont trigger a search? that seems a bit inconvenient to me...
btw, really nice app! some improvements in searching would make it even better 😃

**Comment by fabiospampinato** [comment]
> @fabiospampinato you mean hitting enter wont trigger a search? that seems a bit inconvenient to me...

Exactly, it's not actually, as soon as you don't write anything within 100ms the search is performed, this often leads to a faster search experience.
