### ISSUE TITLE
Bug & improuvment using the search bar

### ISSUE THREAD

**Issue by Topodom** [fabiospampinato/notable#237]
Hi,

Bug :
When i type  a word that is not in a title, i get no results. until here i's OK. But if i type entre then i get a bug (see below)

Improuvment :
It shoul be great if the search tool can search inside the text of the notes.

Cordialy
Dominique

An Error Occurred!
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Error (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:13:314)
    at ca (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at t (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:118:40)
    at af (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:150:11)
    at fg (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:154:21)
    at Q (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:468)
    at Ag (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///C:/Programmes_portables/Notable101/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)
Report It

**Comment by Topodom** [comment]
I am using notable on windows 10

**Comment by mikaelmello** [comment]
> When i type a word that is not in a title, i get no results. until here i's OK.

This does not happen here.  I get as results any notes that contain my search term.

> But if i type entre then i get a bug (see below)

Also cannot reproduce.

I am using Notable 1.1.0 (it seems yours is 1.0.1), have you tried updating?

**Comment by fabiospampinato** [comment]
@Topodom it looks like you're using an older version of the app, this bug has since been fixed.

**Comment by Topodom** [comment]
I have updated to Notable 1.1.0 and everything is OK.

Thanks, for the answer and this great simple software  and super useful
