### ISSUE TITLE
Improve support for invalid title and metadata in general

### ISSUE THREAD

**Issue by Trenar** [fabiospampinato/notable#240]
OS: Ubuntu 18.04

I'm no more able to start Notable. When starting, I can see the UI for a fraction of seconds, but then I only see the attached error message. Yesterday anything went well.
Reinstalling the .deb package or using the AppImage doesn't work either.
```
An Error Occurred!
TypeError: text.replace is not a function
    at showdown.Converter.makeHtml (/opt/Notable/resources/app.asar/node_modules/showdown/dist/showdown.js:2459:17)
    at Object.makeHtml (file:///opt/Notable/resources/app.asar/webpack:/src/renderer/utils/markdown.ts:191:37)
    at Object.memoized [as render] (/opt/Notable/resources/app.asar/node_modules/lodash/lodash.js:10553:27)
    at render (file:///opt/Notable/resources/app.asar/webpack:/src/renderer/components/main/middlebar/note.tsx:14:25)
    at d (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:102)
    at Ag (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)
    at Qh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:216:196)
```

**Comment by Trenar** [comment]
Hi @fabiospampinato , thanks a lot for your quick reply. Indeed, I tried to create a note with a wrong formatted title.

PS: Thank you very much for this awesome work!

**Comment by fabiospampinato** [comment]
I'm reopening this as the app shouldn't crash for such things. What title were you using?

**Comment by Trenar** [comment]
I think it was my fault. I try to write a script, that creates notes based on a template every day, I'm using Notable at work. I simply forgot the string delimiters in the md header. e.g.
`title: 2019-01-08`
instead of
`title '2019-01-08'`

**Comment by fabiospampinato** [comment]
@Trenar thanks for the info!

**Comment by fabiospampinato** [comment]
Thins like `tags: [A/B]]` crash the app too, we should be more resilient against this cases.
