### ISSUE TITLE
TypeError: Cannot read property 'isAlwaysOnTop' of undefined

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#287]
- **OS Version**: Windows 10 x64
- **Notable Version**: master 94795f8dbdd7843cd315136444dc66e0bc73057b

### Current behavior
When switching a data directory:
```
Exception has occurred: TypeError
TypeError: Cannot read property 'isAlwaysOnTop' of undefined
    at Main.initMenu (c:\notable\src\main\windows\main.ts:318:31)
    at Main.__flagsUpdate (c:\notable\src\main\windows\main.ts:418:10)
    at EventEmitter.emit (events.js:187:15)
    at WebContents.<anonymous> (C:\notable\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:284:13)
    at WebContents.emit (events.js:182:13)
```
Caused by 9013e2c672595989187297db2fc64d416adf31a8

### Expected behavior
When switching a data directory, it should not crash.

**Comment by fabiospampinato** [comment]
Good catch, thank you! We should check if a window actually exists.
