### ISSUE TITLE
renderer doesn't compile

### ISSUE THREAD

**Issue by dps** [fabiospampinato/notable#41]
This is a DUP of Issue #6 which is marked closed, but I have verified that it's still a problem. Any ideas?

Mac OS X 10.14

```
$ npm run svelto:dev

> notable@1.0.0 svelto:dev /Users/dps/notable
> svelto build --env development
```

followed by
```
$ npm run dev
```

produces the error:
```
  ERROR in ./src/renderer/render.tsx
  Module not found: Error: Can't resolve '@static/css/notable.min.css' in '/Users/dps/notable/src/renderer'
   @ ./src/renderer/render.tsx 37:0-37
   @ ./src/renderer/index.ts
   @ multi (webpack)-dev-server/client?http://localhost:9080 (webpack)/hot/dev-server.js css-hot-loader/hotModuleReplacement ./src/renderer/index.ts
  
  ERROR in ./src/renderer/render.tsx
  Module not found: Error: Can't resolve '@static/javascript/notable.min.js' in '/Users/dps/notable/src/renderer'
   @ ./src/renderer/render.tsx 38:0-43
   @ ./src/renderer/index.ts
   @ multi (webpack)-dev-server/client?http://localhost:9080 (webpack)/hot/dev-server.js css-hot-loader/hotModuleReplacement ./src/renderer/index.ts
```

**Comment by leiy3** [comment]
I am also seeing the same issue on OSX 10.14.

**Comment by RomanKornev** [comment]
Also doesn't work on Windows 10 x64 1803.

**Comment by fabiospampinato** [comment]
There should definitely be more output generated by `npm run svelto:dev`, or at least an error. I'll look into that.

**Comment by fabiospampinato** [comment]
@dps  yes actually, can you post the output of the following command: `npx svelto --env development --fresh --verbose`?

**Comment by dps** [comment]
It produces no output at all:
```
$ npx svelto --env development --fresh --verbose
$
```

**Comment by dps** [comment]
same result when executing `npx -c "svelto --env development --fresh --verbose"` if that is also of interest.

**Comment by RomanKornev** [comment]
@fabiospampinato  Here is my output on Windows 10 x64 1803:
```
$ npx svelto --env development --fresh --verbose
The system cannot find the path specified.
```

**Comment by fabiospampinato** [comment]
🤔 that's strange. I don't have time for fixing this today, but I consider it a pretty important issues as without it contributing can be challenging. Until this is fixed I've published the compiled css/js into the repo, [here](https://github.com/fabiospampinato/notable/tree/master/src/renderer/template/dist). you should now be able to start-up the app without needing to compile Svelto yourself.

**Comment by fabiospampinato** [comment]
If anyone wants to help debugging this I would recommend attaching the debugger in `node_modules/svelto/bin/index.js`, [svelto](https://github.com/svelto/svelto) uses [pacco](https://github.com/fabiospampinato/pacco) under the hood so my guess would be that the problem is there somewhere.

**Comment by dps** [comment]
Looking...

Changed the `pacco` invocation to something which logs the output:

```
execa ( 'pacco', args, opts ).then(result => {
  console.log(result.stdout);
});
```
Produces:
```
$ npx svelto --env development --fresh --verbose
(node:39439) UnhandledPromiseRejectionWarning: Error: spawn pacco ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
(node:39439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dps** [comment]
So possibly as since as pacco not being listed as a dependency? It's not in my `node_modules`.

**Comment by dps** [comment]
Just to confirm - doing `npm install pacco` followed by `npm run dev` resulted in a successful compile.

**Comment by RomanKornev** [comment]
Issue is still present even after installing `pacco`.
#18 is blocked as a result.

**Comment by gunt3001** [comment]
I can confirm the issue is fixed once `pacco` is installed, on macOS, but..

> Issue is still present even after installing `pacco`.

I'm assuming @RomanKornev is referring to Windows, in which I can also confirm I'm still getting `The system cannot find the path specified.` when running svelto on Windows.

**Comment by fabiospampinato** [comment]
We are now including `pacco` as a proper dependency.

I can also reproduce "The system cannot find the path specified." on Windows, fix (hopefully) coming soon.

**Comment by fabiospampinato** [comment]
There's an issue with the `>` character.

I can't spawn `pacco` with the following args under Windows:

```js
const args = [ 'pacco', 'config', '--config', '{"browsers":["ie >= 9"]}' ];
```

If I remove the `>` character it works. I tried escaping it but I always get the same error.

I could `base64` encode JSON objects to workaround this problem, but I'd rather find a proper fix, if anyone has any idea how to fix this please do let me know.

**Comment by gunt3001** [comment]
It seems on Windows `>` can be escaped with a triple `^` like so `"ie ^^^>= 10"`. With that I could get it to compile on Windows.

I still feel like there could be a better solution, but it's an option.

**Comment by RomanKornev** [comment]
If anyone still has issues compiling:
`Failed to load "notable\eyJicm93c2VycyI6WyJpZSA..."` - just re-clone the repository again.

**Comment by gunt3001** [comment]
> Seriously? Another reason for hating Windows, what is that syntax 😨 @gunt3001 do you know where this is documented? I couldn't find anything particularly interesting by searching for "triple caret escape" on Google.

The escape character is actually just one caret `^`. However in some cases the command can get parsed several times, so you need to escape the caret itself. This [SO answer](https://stackoverflow.com/questions/251557/escape-angle-brackets-in-a-windows-command-prompt/26041395#26041395) explains it a bit (and escape characters in general).

**Comment by fabiospampinato** [comment]
@gunt3001 thanks for the link! Issues like this shouldn't happen in the future as we are now encoding JSON objects (which can contain basically any character) as base64 for more reliable compatibility.
